=== nguyenhongphat0/fpt8/xml/DemoXSL/build/classes/testxsl/schema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema xmlns="https://hongphat.sunrise.vn" targetNamespace="https://hongphat.sunrise.vn"
            version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:complexType name="author">
        <xs:sequence>
            <xs:element name="published">
                <xs:complexType mixed="true">
                    <xs:choice>
                        <xs:sequence>
                        </xs:sequence>
                        <xs:sequence>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="hate" type="xs:string"/>
                        </xs:sequence>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="updated"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="feed">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entry" maxOccurs="10">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="price" type="xs:boolean"></xs:element>
                            <xs:element name="author" type="author">
                            </xs:element>
                            <xs:element name="summary">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="type" type="xs:normalizedString"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string"></xs:attribute>
                        <xs:attribute name="saleoff" type="xs:decimal"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nguyenhongphat0/fpt8/xml/TestXSL/src/testxsl/feed.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<feed xmlns="https://hongphat.sunrise.vn"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://hongphat.sunrise.vn schema.xsd">
    <entry id="123" saleoff="-100">
        <title type="html">Arena of Evolution has reportedly rolled out in more territories</title>
        <price>1</price>
        <author>
            <published>2019<author>a</author>-05-08T06:29:3<hate>shit</hate>6+00:00</published>
            <updated>2019-05-08T06:29:36+00:00</updated>
        </author>
        <summary type="html">Arena of Evolution, the Auto Chess rip-off that soft launched on Android recently, has reportedly rolled out in more territories. It doesn&#8217;t seem to be a full global release but players in America and Germany are reporting that it&#8217;s available in their countries now. Arena of Evolution is basically Auto Chess on mobile If you haven&#8217;t heard of this yet, it&#8217;s a new strategy game that draws an awful lot of inspiration from Auto Chess. That&#8217;s a Dota spin-off in which you set all of your strategical options before the battle and then watch it play out. It&#8217;s pretty novel. There are over 60 heroes to collect here, all of which you can upgrade to increase their power or simply customise their play style. If you&#8217;d like to check it out, it&#8217;s available in certain territories right now on Google Play. As ever, please let us know in the comments section below if you can or can&#8217;t get it so the audience has a good idea of where it&#8217;s available.</summary>
    </entry>
    <entry id="618">
        <title type="html">First guide</title>
        <price>0</price>
        <author>
            <published>2019-05-08T06:29:36+00:00</published>
            <updated>2019-05-08T06:29:36+00:00</updated>
        </author>
        <summary type="html">Arena of Evolution, the Auto Chess rip-off that soft launched on Android recently, has reportedly rolled out in more territories. It doesn&#8217;t seem to be a full global release but players in America and Germany are reporting that it&#8217;s available in their countries now. Arena of Evolution is basically Auto Chess on mobile If you haven&#8217;t heard of this yet, it&#8217;s a new strategy game that draws an awful lot of inspiration from Auto Chess. That&#8217;s a Dota spin-off in which you set all of your strategical options before the battle and then watch it play out. It&#8217;s pretty novel. There are over 60 heroes to collect here, all of which you can upgrade to increase their power or simply customise their play style. If you&#8217;d like to check it out, it&#8217;s available in certain territories right now on Google Play. As ever, please let us know in the comments section below if you can or can&#8217;t get it so the audience has a good idea of where it&#8217;s available.</summary>
    </entry>
</feed>
